# Family-wise Error Correction

## AFNI 3dClustSim

As outlined in Cox et al. (2017, Brain Connectivity), the conventional Gaussian random field theory approach to cluster correction in fMRI 
analysis is anticonservative in many cases because the empirical autocorrelation function of noise in fMRI has a much longer tail than the 
Gaussian distribution would predict. This was highlighted in Woo & Wager (2014) and elaborated by Eklund (2016, to greater effect).

There are a couple of improvements proposed and tested by Cox to control the familywise error rate to (nearly) .05. The package supports both
of these methods. Let's do a quick walkthrough.

### AFNI 3dClustSim + 3dFWHMx -ACF

The basic approach to 3dClustSim (using -fwhm or -fwhmxyz) assumes a Gaussian-distributed noise structure. As noted above, this is not
realistic in fMRI data. The first correction attempts to overcome the assumption of Gaussianity by fitting a long-tailed distribution
to the noise structure of empirical data. Specifically, one passes in the first-level GLM residuals (one volume per timepoint) as inputs to
3dFWHMx and includes the -ACF flag. This flag will estimate the autocorrelation function from the data by fitting parameters of a mono-exponential
+ Gaussian mixture that can better accommodate the long-tailed spatial autocorrelations in fMRI data.

3dFWHMx produces ACF parameters for every volume in each run's residuals file. The usual approach (per AFNI) is to take the average of these
parameters per run as the best estimate of the spatial structure of noise in that run. Then, to estimate cluster correction thresholds in
3dClustSim, one further averages these run-averaged ACF parameters across all runs to achieve an overall ACF for the entire dataset. In
Cox et al., 2017, the median ACF parameters across datasets are input to 3dClustSim -- I suppose the mean could work, too, depending on whether
there are outliers that would sway it. The estimated values of this averaged 3-parameter ACF are passed to 3dClustSim with the -acf argument.

Based on the -acf input, 3dClustSim now estimates null datasets that have the spatial distribution of noise derived from the empirical data,
which better controls for FWE relative to the standard Gaussian assumption/distribution. Cox and colleagues show that at reasonable voxelwise
thresholds (p < .005 or p < .001), the -ACF approach is close to the nominal .05 alpha level (4 - 8%) when a) the spatial smoothing kernel is > 4mm FWHM,
and b) the test/contrast comes from an event-related design with many repeats of relatively brief stimuli. The false positive rate (FPR) for
block designs and small smoothing kernels (4mm FWHM) are worse, sometimes > 15%. Also, note that a voxelwise threshold of .01 or more (e.g., .02)
is far too generous for cluster correction and should be avoided in general (see Woo and Wager for more info). The above summary is depicted in Cox
et al., 2017, Fig 1 G, H, I.

#### Implementing the -ACF correction in fmri.pipeline

**Example 1: Setting up 3dFWHMx yourself**

If you would like to run 3dFWHMx yourself using the afni_3dfwhmx wrapper class, here is an example:

```
# example FEAT LVL1 output
path <- "/proj/mnhallqlab/studies/MMClock/MR_Proc/10637_20140304/mni_5mm_aroma/sceptic_vchosen_ventropy_dauc_pemax_vtime_preconvolve/FEAT_LVL1_run1.feat"
res4d_file <- file.path(path, "stats", "res4d.nii.gz")
fwhmx_mask_file <- file.path(path, "mask.nii.gz")

test <- afni_3dfwhmx$new(input_file = res4d_file, mask_file = fwhmx_mask_file, average = "geometric")
test$run() # will run 3dFWHMx in the local compute environment (use force = TRUE to re-run completed file)
test$is_complete()
test$get_acf_params() # average ACF params
test$get_fwhm_by_volume() # FWHM for each sub-brik (volume)
test$get_acf_by_radius() # FWHM for each sub-brik (volume)
test$remove_outputs(prompt = TRUE) # delete files generated by this input -- it will ask you to confirm each
```

**Example 2: Running 3dFWHMx for a list of files**

The afni_3dfwhmx class is a wrapper around 

```
# get ACF parameters for 8 first-level residual files for testing
path <- "/proj/mnhallqlab/studies/MMClock/MR_Proc/10637_20140304/mni_5mm_aroma/sceptic_vchosen_ventropy_dauc_pemax_vtime_preconvolve"
res4d_files <- list.files(pattern = "res4d.nii.gz", path = path, full.names = T, recursive = T)
fwhmx_mask_files <- list.files(pattern = "mask.nii.gz", path = path, full.names = T, recursive = T)
test <- afni_3dfwhmx_list$new(input_files = res4d_files, mask_files = fwhmx_mask_files, scheduler = "slurm")

# average a, b, c parameters across datasets
test$get_acf_average()

# average effective FWHM estimate using -ACF
test$get_effective_fwhm()

# per-dataset ACF summary
test$get_acf_df()

```

