# Tests for the feat_killed trap logic generated by run_feat_sepjobs.
#
# The trap must:
#   1. Iterate all_odirs (every output directory for the job)
#   2. Skip directories that already have .feat_complete
#   3. Write .feat_fail only to directories that are still in-flight or not started

# ---------------------------------------------------------------------------
# Helper: build a minimal bash script that defines all_odirs and feat_killed,
# then immediately calls feat_killed (simulating SIGTERM delivery).
# ---------------------------------------------------------------------------
build_trap_script <- function(odir_paths) {
  c(
    "#!/bin/bash",
    paste0("all_odirs=(", paste0("\"", odir_paths, "\"", collapse = " "), ")"),
    "job_id=test_job_id",
    "",
    "function feat_killed() {",
    "  kill_time=$( date )",
    "  for _odir in \"${all_odirs[@]}\"; do",
    "    [ -f \"${_odir}/.feat_complete\" ] && continue",
    "    echo \"$kill_time\" > \"${_odir}/.feat_fail\"",
    "  done",
    "  exit 1",
    "}",
    "",
    "feat_killed"
  )
}

# ---------------------------------------------------------------------------
# L1: multiple .feat dirs per job, some already complete
# ---------------------------------------------------------------------------
test_that("feat_killed marks only incomplete L1 .feat dirs as failed", {
  tmp <- withr::local_tempdir()

  # Simulate 4 feat output directories (4 runs for one subject)
  odirs <- file.path(tmp, paste0("FEAT_LVL1_run", 1:4, ".feat"))
  for (d in odirs) dir.create(d, recursive = TRUE)

  # Suppose runs 1 and 3 completed before SIGTERM
  writeLines("done", file.path(odirs[1], ".feat_complete"))
  writeLines("done", file.path(odirs[3], ".feat_complete"))

  # Write and execute the trap script
  script <- file.path(tmp, "trap_test.sh")
  writeLines(build_trap_script(odirs), script)
  Sys.chmod(script, "0755")
  system2("bash", script) # exit code 1 expected

  # Runs 1 and 3 should NOT have .feat_fail (they completed)
  expect_false(file.exists(file.path(odirs[1], ".feat_fail")))
  expect_false(file.exists(file.path(odirs[3], ".feat_fail")))

  # Runs 2 and 4 should have .feat_fail
  expect_true(file.exists(file.path(odirs[2], ".feat_fail")))
  expect_true(file.exists(file.path(odirs[4], ".feat_fail")))

  # .feat_complete on runs 1 and 3 should be untouched
  expect_true(file.exists(file.path(odirs[1], ".feat_complete")))
  expect_true(file.exists(file.path(odirs[3], ".feat_complete")))
})

# ---------------------------------------------------------------------------
# L1: no directories completed — all should get .feat_fail
# ---------------------------------------------------------------------------
test_that("feat_killed marks all L1 dirs as failed when none completed", {
  tmp <- withr::local_tempdir()

  odirs <- file.path(tmp, paste0("FEAT_LVL1_run", 1:4, ".feat"))
  for (d in odirs) dir.create(d, recursive = TRUE)

  script <- file.path(tmp, "trap_test.sh")
  writeLines(build_trap_script(odirs), script)
  Sys.chmod(script, "0755")
  system2("bash", script)

  for (d in odirs) {
    expect_true(file.exists(file.path(d, ".feat_fail")), info = d)
    expect_false(file.exists(file.path(d, ".feat_complete")), info = d)
  }
})

# ---------------------------------------------------------------------------
# L1: all directories completed — none should get .feat_fail
# ---------------------------------------------------------------------------
test_that("feat_killed does not overwrite .feat_complete on fully finished L1 job", {
  tmp <- withr::local_tempdir()

  odirs <- file.path(tmp, paste0("FEAT_LVL1_run", 1:4, ".feat"))
  for (d in odirs) {
    dir.create(d, recursive = TRUE)
    writeLines("done", file.path(d, ".feat_complete"))
  }

  script <- file.path(tmp, "trap_test.sh")
  writeLines(build_trap_script(odirs), script)
  Sys.chmod(script, "0755")
  system2("bash", script)

  for (d in odirs) {
    expect_true(file.exists(file.path(d, ".feat_complete")), info = d)
    expect_false(file.exists(file.path(d, ".feat_fail")), info = d)
  }
})

# ---------------------------------------------------------------------------
# L3: single .gfeat dir per job
# ---------------------------------------------------------------------------
test_that("feat_killed marks single incomplete L3 .gfeat dir as failed", {
  tmp <- withr::local_tempdir()

  odirs <- file.path(tmp, "model_contrast.gfeat")
  dir.create(odirs, recursive = TRUE)

  script <- file.path(tmp, "trap_test.sh")
  writeLines(build_trap_script(odirs), script)
  Sys.chmod(script, "0755")
  system2("bash", script)

  expect_true(file.exists(file.path(odirs, ".feat_fail")))
  expect_false(file.exists(file.path(odirs, ".feat_complete")))
})

# ---------------------------------------------------------------------------
# L3: single .gfeat dir that already completed — should not get .feat_fail
# ---------------------------------------------------------------------------
test_that("feat_killed skips completed L3 .gfeat dir", {
  tmp <- withr::local_tempdir()

  odirs <- file.path(tmp, "model_contrast.gfeat")
  dir.create(odirs, recursive = TRUE)
  writeLines("done", file.path(odirs, ".feat_complete"))

  script <- file.path(tmp, "trap_test.sh")
  writeLines(build_trap_script(odirs), script)
  Sys.chmod(script, "0755")
  system2("bash", script)

  expect_true(file.exists(file.path(odirs, ".feat_complete")))
  expect_false(file.exists(file.path(odirs, ".feat_fail")))
})
