#' Setup a first-level SPM model using a build_design_matrix object
#'
#' @param d_obj a single-subject design matrix object generated by build_design_matrix
#' @param gpa a gpa (glm_pipeline_arguments) object generated by setup_glm_pipeline
#' @param model_name a string indicating the model name within \code{gpa} to setup. If
#'   you wish to setup multiple models, this is handled upstream in setup_l1_models.R
#' @param l1_confound_files optional character vector of nuisance regressor files,
#'   one per run, to include in SPM's multi_reg field
#' @param run_nifti optional character vector of NIfTI filenames used in l1 analysis.
#'   Prefer to pass these via the build_design_matrix object in $run_nifti
#' @param execute_spm whether to execute SPM setup/estimation immediately. Default: FALSE
#'
#' @importFrom checkmate assert_class assert_string assert_character assert_file_exists
#' @importFrom lgr get_logger
#' @importFrom data.table fread
#' @author Michael Hallquist
#' @export
#'
spm_l1_model <- function(
  id = NULL, session = NULL, l1_confound_files = NULL, d_obj, gpa,
  model_name = NULL, run_nifti = NULL, execute_spm = FALSE
) {

  checkmate::assert_scalar(id, null.ok = FALSE)
  checkmate::assert_scalar(session, null.ok = FALSE)
  checkmate::assert_character(l1_confound_files, null.ok = TRUE)
  checkmate::assert_class(d_obj, "bdm")
  checkmate::assert_class(gpa, "glm_pipeline_arguments")
  checkmate::assert_string(model_name) # single string

  lg <- lgr::get_logger("glm_pipeline/l1_setup")
  lg$set_threshold(gpa$lgr_threshold)

  if (!is.null(d_obj$run_nifti)) {
    lg$debug("Using internal NIfTI files (run_nifti) within d_obj for SPM level 1 setup")
    run_nifti <- d_obj$run_nifti
  } else if (!is.null(d_obj$run_niftis)) {
    lg$debug("Using internal NIfTI files (run_niftis) within d_obj for SPM level 1 setup")
    run_nifti <- d_obj$run_niftis
  }

  if (is.null(run_nifti)) {
    msg <- "spm_l1_model requires run_nifti either in d_obj or passed explicitly."
    lg$error(msg)
    stop(msg)
  }

  if (!is.null(l1_confound_files) && length(l1_confound_files) != length(run_nifti)) {
    if (length(l1_confound_files) == 1L) {
      lg$warn("Single l1_confound_file provided for multi-run data; replicating to match runs.")
      l1_confound_files <- rep(l1_confound_files, length(run_nifti))
    } else {
      msg <- "Length of l1_confound_files must match length of run_nifti."
      lg$error(msg)
      stop(msg)
    }
  }

  stopifnot(length(run_nifti) == length(d_obj$run_volumes)) # need these to align
  checkmate::assert_character(run_nifti, null.ok = FALSE)
  checkmate::assert_file_exists(run_nifti) # all exist

  stopifnot(model_name %in% names(gpa$l1_models$models))

  spm_l1_output_dir <- get_output_directory(
    id = id, session = session, l1_model = model_name,
    gpa = gpa, glm_software = "spm", what = "l1"
  )

  lg$info("Create l1 spm_l1_output_dir: %s", spm_l1_output_dir)
  dir.create(spm_l1_output_dir, showWarnings = FALSE, recursive = TRUE)

  spm_defaults <- list(
    hpf = 100,
    hrf_derivs = "none",
    condition_contrasts = TRUE,
    unit_contrasts = TRUE,
    effects_of_interest_F = TRUE,
    spm_execute_setup = FALSE,
    spm_execute_glm = FALSE,
    spm_execute_contrasts = FALSE,
    concatenate_runs = NULL,
    cleanup_tmp = FALSE,
    nifti_tmpdir = NULL,
    spm_path = NULL,
    force_l1_creation = FALSE
  )

  spm_settings <- populate_defaults(gpa$glm_settings$spm, spm_defaults)
  spm_compute_env <- get_compute_environment(gpa, c("spm"))

  if (is.null(spm_settings$concatenate_runs)) {
    spm_settings$concatenate_runs <- length(run_nifti) > 1L
  }

  if (is.null(spm_settings$nifti_tmpdir)) {
    spm_settings$nifti_tmpdir <- file.path(spm_l1_output_dir, "nifti_tmp")
  }

  if (isTRUE(execute_spm)) {
    spm_settings$spm_execute_setup <- TRUE
    spm_settings$spm_execute_glm <- TRUE
    spm_settings$spm_execute_contrasts <- TRUE
  }

  # Determine confounds handling for SPM
  ts_files <- NULL
  if (!is.null(l1_confound_files)) {
    valid_confound <- !is.na(l1_confound_files) & nzchar(l1_confound_files) & file.exists(l1_confound_files)

    if (all(valid_confound)) {
      if (isTRUE(spm_settings$concatenate_runs) && length(l1_confound_files) > 1L) {
        lg$info("Concatenating confound files for SPM concatenated runs")
        confounds_list <- lapply(l1_confound_files, function(ff) {
          data.table::fread(ff, header = FALSE, data.table = FALSE)
        })
        confounds_concat <- do.call(rbind, confounds_list)
        concat_file <- file.path(spm_l1_output_dir, "l1_confounds_concat.txt")
        write.table(confounds_concat, file = concat_file, row.names = FALSE, col.names = FALSE)
        # replicate to satisfy generate_spm_mat length check; only first element used when concatenated
        ts_files <- rep(concat_file, length(run_nifti))
      } else {
        ts_files <- l1_confound_files
      }
    } else {
      lg$warn("Some l1_confound_files are missing or invalid; disabling confounds for SPM setup.")
    }
  }

  # Ensure SPM uses the run_niftis field
  if (is.null(d_obj$run_niftis)) d_obj$run_niftis <- run_nifti

  spm_status <- get_spm_status(spm_l1_output_dir, lg = lg)

  spm_syntax <- NULL
  if (isTRUE(spm_status$spm_mat_exists) && isFALSE(spm_settings$force_l1_creation)) {
    lg$info("SPM.mat exists in %s. Skipping SPM design setup (force_l1_creation = FALSE).", spm_l1_output_dir)
  } else {
    lg$info("Generating SPM batch scripts for model: %s", model_name)
    spm_syntax <- tryCatch(
      {
        generate_spm_mat(
          bdm = d_obj, ts_files = ts_files, output_dir = spm_l1_output_dir,
          hpf = spm_settings$hpf, hrf_derivs = spm_settings$hrf_derivs,
          nifti_tmpdir = spm_settings$nifti_tmpdir, cleanup_tmp = spm_settings$cleanup_tmp,
          condition_contrasts = spm_settings$condition_contrasts,
          unit_contrasts = spm_settings$unit_contrasts,
          effects_of_interest_F = spm_settings$effects_of_interest_F,
          spm_execute_setup = spm_settings$spm_execute_setup,
          spm_execute_glm = spm_settings$spm_execute_glm,
          spm_execute_contrasts = spm_settings$spm_execute_contrasts,
          concatenate_runs = spm_settings$concatenate_runs,
          spm_path = spm_settings$spm_path,
          matlab_cmd = spm_settings$matlab_cmd,
          matlab_args = spm_settings$matlab_args,
          compute_env = spm_compute_env
        )
      },
      error = function(e) {
        lg$error("Problem running generate_spm_mat for model %s: %s", model_name, as.character(e))
        return(NULL)
      }
    )
  }

  spm_status <- get_spm_status(spm_l1_output_dir, lg = lg)

  spm_l1_df <- data.frame(
    id = id, session = session,
    l1_model = model_name,
    spm_dir = spm_l1_output_dir, # explicitly named for clarity in run_spm_sepjobs
    n_runs = length(run_nifti),
    run_nifti = I(list(run_nifti)),
    run_volumes = I(list(d_obj$run_volumes)),
    l1_confound_files = I(list(l1_confound_files)),
    concatenate_runs = spm_settings$concatenate_runs,
    gunzip_cmds = I(list(spm_syntax$gunzip_cmds)),
    contrast_cmds = I(list(spm_syntax$contrast_cmds))
  )

  spm_l1_df <- cbind(spm_l1_df, spm_status)
  spm_l1_df$to_run <- !spm_l1_df$spm_complete

  return(spm_l1_df)
}
